apiVersion: apps/v1 
kind: Deployment
metadata:
  name: predict-imdb 
  namespace: ai-project
  labels:
    app: imdb-server
spec:
  revisionHistoryLimit: 3
  replicas: 1 
  selector:
    matchLabels:
      app: imdb-server
  template:
    metadata:
      labels:
        app: imdb-server
    spec:
      containers:
      - name: imdb-server
        image: tensorflow/tensorflow:latest-devel-py3
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
         - echo "start";
           pip install git
           git clone https://github.com/amirgholipour/imdb_deploy.git;
           cd imdb_deploy;
           pip install -r requirements.txt;
           python server.py;
        ports:
        - containerPort: 8080
          protocol: TCP
